import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { RouteProvider } from '@/providers/route-provider';
import { ThemeProvider } from '@/providers/theme-provider';
import { getMainNavigation, getFooterData } from "@/lib/contentful";
import MainNav from "@/components/blocks/MainNav";
import Footer from "@/components/blocks/Footer"; // <-- footer import

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Traemos la navegación y el footer desde Contentful
  const { logo, items } = await getMainNavigation("main-nav");
  const footerData = await getFooterData();
  console.log("Footer Data:", footerData);


  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        {/* Navegación */}
        <MainNav logo={logo} items={items} />

        {/* Contenido principal */}
        <RouteProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </RouteProvider>

        {/* Footer dinámico */}
        <Footer
          heading={footerData.heading}
          subHeading={footerData.subHeading}
          logoImage={footerData.logoImage}
          footerLinksCollection={footerData.footerLinksCollection}
          socialLinks={footerData.socialLinksCollection.items} // <-- pasar solo el array
        />
      </body>
    </html>
  );
}
